baseurl: ""
url: "http://webinar.soedinennost.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js
yandex_metrika: 38035280
google_analytics: UA-46456269-11
permalink: /:title/

#title: "Николай Воробьёв"
#description: "Помогаю перестать быть такой жалкой тряпкой"
#keywords: "#ШоуВоробьёва"
#author: "Николай Воробьёв"
